/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as OrbRouteImport } from './routes/orb'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorldRouteImport } from './routes/world'
import { Route as WorkIdRouteImport } from './routes/work.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbRoute = OrbRouteImport.update({
  id: '/orb',
  path: '/orb',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdRoute = WorkIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/memory': typeof MemoryRoute
  '/orb': typeof OrbRoute
  '/settings': typeof SettingsRoute
  '/work': typeof WorkRouteWithChildren
  '/world': typeof WorldRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/memory': typeof MemoryRoute
  '/orb': typeof OrbRoute
  '/settings': typeof SettingsRoute
  '/work': typeof WorkRouteWithChildren
  '/world': typeof WorldRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/memory': typeof MemoryRoute
  '/orb': typeof OrbRoute
  '/settings': typeof SettingsRoute
  '/work': typeof WorkRouteWithChildren
  '/world': typeof WorldRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companion'
    | '/memory'
    | '/orb'
    | '/settings'
    | '/work'
    | '/world'
    | '/work/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companion'
    | '/memory'
    | '/orb'
    | '/settings'
    | '/work'
    | '/world'
    | '/work/$id'
  id:
    | '__root__'
    | '/'
    | '/companion'
    | '/memory'
    | '/orb'
    | '/settings'
    | '/work'
    | '/world'
    | '/work/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanionRoute: typeof CompanionRoute
  MemoryRoute: typeof MemoryRoute
  OrbRoute: typeof OrbRoute
  SettingsRoute: typeof SettingsRoute
  WorkRoute: typeof WorkRouteWithChildren
  WorldRoute: typeof WorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orb': {
      id: '/orb'
      path: '/orb'
      fullPath: '/orb'
      preLoaderRoute: typeof OrbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkIdRoute: typeof WorkIdRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkIdRoute: WorkIdRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanionRoute: CompanionRoute,
  MemoryRoute: MemoryRoute,
  OrbRoute: OrbRoute,
  SettingsRoute: SettingsRoute,
  WorkRoute: WorkRouteWithChildren,
  WorldRoute: WorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
